// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Todo struct {
	ID       string `json:"_id" bson:"_id"`
	Activity string `json:"activity" bson:"activity"`
	Detail   string `json:"detail" bson:"detail"`
	User     *User  `json:"user"`
}

type User struct {
	ID       string `json:"_id"`
	Username string `json:"username"`
}

type NewTodo struct {
	Activity string `json:"activity"`
	Detail   string `json:"detail"`
	UserID   string `json:"userID"`
}
